CREATE TABLE QC_USER
(
    USER_ID                   VARCHAR(40)   NOT NULL,
    LOGIN_ID                  VARCHAR(250)  NULL,
    LOGIN_PWD                 VARCHAR(2048) NULL,
    USER_NM                   VARCHAR(200)  NULL,
    USER_NCNM                 VARCHAR(200)  NULL,
    USER_DC                   TEXT          NULL,
    USER_EMAIL                VARCHAR(250)  NULL,
    USER_EMAIL_VERIFY_YN      CHAR(1)       NOT NULL DEFAULT 'N',
    USER_MOBILE               VARCHAR(40)   NULL,
    USER_MOBILE_VERIFY_YN     CHAR(1)       NOT NULL DEFAULT 'N',
    USER_CI_VAL               VARCHAR(2048) NULL,
    USER_DI_VAL               VARCHAR(2048) NULL,
    USER_JOIN_TYPE            VARCHAR(40)   NULL,
    USER_JOIN_CHANNEL         VARCHAR(40)   NULL,
    USER_JOIN_DTTM            DATETIME      NULL,
    USER_LAST_LOGIN_DTTM      DATETIME      NULL,
    USER_LAST_CHANGE_PWD_DTTM DATETIME      NULL,
    USER_LEAVE_DTTM           DATETIME      NULL,
    USER_LEAVE_REASON_CD      VARCHAR(40)   NULL,
    USER_LEAVE_REASON_DC      TEXT          NULL,
    USER_STTUS_CD             VARCHAR(40)   NULL,
    REGIST_DT                 DATETIME      NOT NULL DEFAULT NOW(),
    REGIST_ID                 VARCHAR(40)   NOT NULL DEFAULT 'SYSTEM',
    UPDT_DT                   DATETIME      NOT NULL DEFAULT NOW(),
    UPDT_ID                   VARCHAR(40)   NOT NULL DEFAULT 'SYSTEM',
    CONSTRAINT QC_USER_PK PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX UDX_QC_USER_LOGIN_ID ON QC_USER (LOGIN_ID);
CREATE UNIQUE INDEX UDX_QC_USER_EMAIL ON QC_USER (USER_EMAIL);
CREATE UNIQUE INDEX UDX_QC_USER_MOBILE ON QC_USER (USER_MOBILE);

CREATE TABLE QC_AUTH
(
    AUTH_ID        VARCHAR(40)  NOT NULL,
    AUTH_PARENT_ID VARCHAR(40)  NULL,
    AUTH_CD        VARCHAR(40)  NOT NULL,
    AUTH_NM        VARCHAR(200) NULL,
    AUTH_DC        TEXT         NULL,
    USE_YN         CHAR(1)      NOT NULL DEFAULT 'Y',
    REGIST_DT      DATETIME     NOT NULL DEFAULT NOW(),
    REGIST_ID      VARCHAR(40)  NOT NULL DEFAULT 'SYSTEM',
    UPDT_DT        DATETIME     NOT NULL DEFAULT NOW(),
    UPDT_ID        VARCHAR(40)  NOT NULL DEFAULT 'SYSTEM',
    CONSTRAINT QC_AUTH_PK PRIMARY KEY (AUTH_ID)
);

CREATE TABLE QC_USER_AUTH
(
    USER_ID   VARCHAR(40) NOT NULL,
    AUTH_ID   VARCHAR(40) NOT NULL,
    REGIST_DT DATETIME    NOT NULL DEFAULT NOW(),
    REGIST_ID VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
    UPDT_DT   DATETIME    NOT NULL DEFAULT NOW(),
    UPDT_ID   VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
    CONSTRAINT QC_USER_AUTH_PK PRIMARY KEY (USER_ID, AUTH_ID)
);